development:
  adapter: postgresql
  encoding: unicode
  database: blog_app_dev
  pool: 5
  username: test
  password: test123

test:
  adapter: postgresql
  encoding: unicode
  database: blog_app_testing
  pool: 5
  username: test
  password: test123

production:
  adapter: postgresql
  encoding: unicode
  database: blog_app_productioning
  pool: 5
  username: test
  password: test123
